services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: softpos-keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
    networks:
      - softpos-net

  discovery-server:
    build:
      context: ./infra/discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_PASSWORD=eureka-admin-password
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - softpos-net

  config-server:
    build:
      context: ./infra/config-server
    depends_on:
      discovery-server:
        condition: service_healthy   # won't start until Eureka is actually ready
    networks:
      - softpos-net

networks:
  softpos-net:
    driver: bridge
