server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        # used when you want to use a local directory as a config source 'dev mode'
        native:
          search-locations: file:../config-repo

        # used when you want to use a git repository as a config source 'prod mode'
        # git:
        #   uri: https://github.com/Chouich-Nacereddine/SoftPos/tree/v.0.0.1/infra/config-repo
